### ISSUE TITLE
infrequent crashes and core dumps

### ISSUE THREAD

**Issue by stdbull** [gauteh/lieer#116]
Hi. I've been using (Gmai)lieer for quite a while now, so thank you for the all the hard work. I use lieer with a large mail store (approx 13GB mail data from Gmail plus approx 12GB from legacy MS exchange that was synced with offlineimap). My .notmuch dir is about 6GB. Most of the time, lieer is solid for me, but every so often it dumps core when pushing (very occasionally on pull). I've managed to get a back trace today, which looks like the following, and was from a pull.
<pre>user@machine > gdb -ex r --args python3 /b/git/gmailieer/gmi sync
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...Reading symbols from /usr/lib/debug/.build-id/09/148930900f465f0cb964452b0ac22986fae752.debug...done.
done.
Starting program: /usr/bin/python3 /b/git/gmailieer/gmi sync
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
receiving metadata (65) .........done: 65 its in 00.753s
resolving changes (65) .........done: 65 its in 00.130s
pushing, 0 changed (65) .....reducing batch request size to: 25
....done: 65 its in 13.709s
remote historyId: 44095561
pull: partial synchronization.. (hid: 44094559)
fetching changes .....remote: no 'history' when more pages were indicated.
remote: request failed, increasing delay between requests to: 1 s
pull: failed, re-try in a bit.
done: 200 its in 00.279s
Traceback (most recent call last):
  File "/b/git/gmailieer/gmi", line 8, in <module>
    g.main ()
  File "/b/git/gmailieer/lieer/gmailieer.py", line 155, in main
    args.func (args)
  File "/b/git/gmailieer/lieer/gmailieer.py", line 225, in sync
    self.pull (args, True)
  File "/b/git/gmailieer/lieer/gmailieer.py", line 351, in pull
    self.partial_pull ()
  File "/b/git/gmailieer/lieer/gmailieer.py", line 360, in partial_pull
    for hist in self.remote.get_history_since (self.local.state.last_historyId):
  File "/b/git/gmailieer/lieer/remote.py", line 203, in get_history_since
    raise Remote.NoHistoryException ()
lieer.remote.NoHistoryException
[Inferior 1 (process 19125) exited with code 01]
(gdb) 
</pre>
I hit this doing a gmi sync. If I re-try, it's fine. Pushing a new tag applied to 400 emails works fine as does removing the tag.
Also, what I have noticed over quite a long time using Lieer is that my inbox 'view' using Gmail in my browser does not equate to my notmuch search on tag inbox. By that, I mean that I have way more emails in my Gmail inbox using the web interface than I do if I notmuch search tag:inbox. This seems quite strange to me. Lieer frequently reports that it's doing a partial sync, but I think that's ok...? Can you suggest a way to try and track down the source of the Remote.NoHistoryException and perhaps why my Gmail inbox label and notmuch inbox tag are not the same?
Keep up the great work.
Thanks and regards.

**Comment by gauteh** [comment]
The NoHistoryException happens because the API indicates that there should
be more history, but there is not. We choose to fail on this since it
seemed sketchy to continue on a faulty basis. It is likely though that
there is just some quirk in the gmail API that results in this and that it
is safe to ignore.

The second case is trickier, does it get fixed if you do a full pull (or
push.. depending on what you want?). Somehow the incremental sync got
messed up.

**Comment by gauteh** [comment]
Closing untill further activity. Thanks for the report.
