### ISSUE TITLE
Make -C expand ~user

### ISSUE THREAD

**Issue by skangas** [gauteh/lieer#141]
When passing a path to lieer using -C from a programming language, rather than a shell, it would be nice to be able to use "~" in the path and have it expanded. I get:

```
path: ~/.mail/account.gmail
error: ~/.mail/account.gmail is not a valid path!
Traceback (most recent call last):
  File "/home/skangas/src/lieer/gmi", line 8, in <module>
    g.main ()
  File "/home/skangas/src/lieer/lieer/gmailieer.py", line 182, in main
    args.func (args)
  File "/home/skangas/src/lieer/lieer/gmailieer.py", line 681, in send
    self.setup (args, args.dry_run, True, True)
  File "/home/skangas/src/lieer/lieer/gmailieer.py", line 223, in setup
    raise NotADirectoryError("error: %s is not a valid path!" % args.path)
NotADirectoryError: error: ~/.mail/account.gmail is not a valid path!
```

This is just a small quality of life improvement.  Thanks.

**Comment by gauteh** [comment]
Agree, want to try implementing?

tir. 5. mai 2020, 20:38 skrev Stefan Kangas <notifications@github.com>:

**Comment by julian-klode** [comment]
Your shell does that automatically for you unless you quote the argument.
