### ISSUE TITLE
Every lieer operation gives "The caller does not have permission" on /discovery

### ISSUE THREAD

**Issue by glittershark** [gauteh/lieer#161]
```
Traceback (most recent call last):
  File "/nix/store/176qqs9airzbwplms3lsprsa73wl7mql-lieer-1.2/bin/.gmi-wrapped", line 25, in <module>
    g.main ()
  File "/nix/store/176qqs9airzbwplms3lsprsa73wl7mql-lieer-1.2/lib/python3.7/site-packages/lieer/gmailieer.py", line 206, in main
    args.func (args)
  File "/nix/store/176qqs9airzbwplms3lsprsa73wl7mql-lieer-1.2/lib/python3.7/site-packages/lieer/gmailieer.py", line 231, in authorize
    self.remote.authorize (args.force)
  File "/nix/store/176qqs9airzbwplms3lsprsa73wl7mql-lieer-1.2/lib/python3.7/site-packages/lieer/remote.py", line 406, in authorize
    self.service = discovery.build ('gmail', 'v1', http = self.http)
  File "/nix/store/z94c9rkxx3413708waig8pnrr1dnkwz8-python3.7-google-api-python-client-1.8.4/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/nix/store/z94c9rkxx3413708waig8pnrr1dnkwz8-python3.7-google-api-python-client-1.8.4/lib/python3.7/site-packages/googleapiclient/discovery.py", line 241, in build
    raise e
  File "/nix/store/z94c9rkxx3413708waig8pnrr1dnkwz8-python3.7-google-api-python-client-1.8.4/lib/python3.7/site-packages/googleapiclient/discovery.py", line 225, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey
  File "/nix/store/z94c9rkxx3413708waig8pnrr1dnkwz8-python3.7-google-api-python-client-1.8.4/lib/python3.7/site-packages/googleapiclient/discovery.py", line 285, in _retrieve_discovery_doc
    raise HttpError(resp, content, uri=actual_url)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest returned "The caller does not have permission">
```

**Comment by kotfic** [comment]
Also seeing this behavior

**Comment by gauteh** [comment]
Yeah. Me too. Seems to have started today. Maybe API keys got blocked?

**Comment by gauteh** [comment]
Seems like this might be an internal bug: https://issuetracker.google.com/issues/160441983 and https://stackoverflow.com/questions/62718002/intermittent-error-while-calling-gmail-api-the-caller-does-not-have-permissio

I have tried cleaning out the `.credentials.gmailieer.json` file and re-authenticated. Let us see what happens on the bug.

**Comment by mjg** [comment]
> I have tried cleaning out the `.credentials.gmailieer.json` file and re-authenticated. Let us see what happens on the bug.

Does a new API key help?

**Comment by gauteh** [comment]
Doubtful, it took forever to get this API key approved. My first thought
was that the API key had been revoked, but I think the issue is the google
issue linked before. You could always try with a private API key (and it
might work).

**Comment by gauteh** [comment]
There is a frantic discussion on https://issuetracker.google.com/issues/160441983, so if you want to keep tabs on whats going on star the issue there.

**Comment by mjg** [comment]
> Doubtful, it took forever to get this API key approved. My first thought was that the API key had been revoked, but I think the issue is the google issue linked before. You could always try with a private API key (and it might work).

Yes, sorry for misphrasing. I meant the private API key.

**Comment by julian-klode** [comment]
Heh, I saw the bug opening, but that was the last time it synced (19:03 CEST [UTC+2] today). 19:08 run got 403.

**Comment by builder7777** [comment]
Cleaning out API keys doesn't help. I tried a new gmail account, new api key, tried service account - nothing works

**Comment by gauteh** [comment]
Seems like it is working again now.

**Comment by gauteh** [comment]
Fixed upstream.
