### ISSUE TITLE
Error with dry run on pull

### ISSUE THREAD

**Issue by arjunkc** [gauteh/lieer#169]
Hi, I'm getting the following error when running

```
gmi pull --dry-run
```

```
(ins)name@namedesktop :account.gmail-name$ gmi pull --dry-run
dry-run:  True
pull: full synchronization (no previous synchronization state)
fetching messages: 3323it [00:05, 631.82it/s]                                                                                 
removing deleted: 0it [00:00, ?it/s]
receiving content:   0%|                                                                   | 1/3323 [00:01<1:50:35,  2.00s/it]missing file: reloading cache to check for changes..Traceback (most recent call last):
  File "/usr/local/bin/gmi", line 24, in <module>
    g.main ()
  File "/usr/local/lib/python3.7/site-packages/lieer/gmailieer.py", line 206, in main
    args.func (args)
  File "/usr/local/lib/python3.7/site-packages/lieer/gmailieer.py", line 404, in pull
    self.full_pull ()
  File "/usr/local/lib/python3.7/site-packages/lieer/gmailieer.py", line 624, in full_pull
    updated = self.get_content (message_gids)
  File "/usr/local/lib/python3.7/site-packages/lieer/gmailieer.py", line 690, in get_content
    self.remote.get_messages (need_content, _got_msgs, 'raw')
  File "/usr/local/lib/python3.7/site-packages/lieer/remote.py", line 133, in func_wrap
    return func (self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/lieer/remote.py", line 369, in get_messages
    cb (msg_batch)
  File "/usr/local/lib/python3.7/site-packages/lieer/gmailieer.py", line 688, in _got_msgs
    self.local.store (m, db)
  File "/usr/local/lib/python3.7/site-packages/lieer/local.py", line 524, in store
    self.update_tags (m, p, db)
  File "/usr/local/lib/python3.7/site-packages/lieer/local.py", line 569, in update_tags
    fname = os.path.join (self.md, self.gids[gid])
KeyError: '17388d8983b0be43'
receiving content:   0%|                                                                   | 1/3323 [00:02<1:52:41,  2.04s/it]
```

**Comment by gauteh** [comment]
Which version of lieer do you have?

søn. 26. jul. 2020, 05:19 skrev Arjun <notifications@github.com>:

**Comment by arjunkc** [comment]
Version 1.2, installed with pip. Should I be on the master branch instead?

**Comment by gauteh** [comment]
No, think that should work on 1.2

søn. 26. jul. 2020, 16:05 skrev Arjun <notifications@github.com>:

**Comment by arjunkc** [comment]
I simply tried running

gmi pull

and it seems to complete successfully. The problem appears to be the
--dry-run option.

**Comment by gauteh** [comment]
Ok, the we should fix the dry run as well.
