### ISSUE TITLE
September 9, 2020 - I suddenly started getting a JSONDecodeError

### ISSUE THREAD

**Issue by markgalassi** [gauteh/lieer#177]
I'm using the version of gmailieer (0.10-1) installed on ubuntu 20.04, but I also confirm with the current git clone from here installed with "python3 setup.py install" or with building a wheel and installing it with pip3.

Yesterday (September 9, 2020) I suddenly started getting a JSONDecodeError - full dump is below.  "gmi auth" gives similar errors.

If this were a sudden change in gmail's protocols then I would have thought I would see more indication of it.  Is it something I'm doing?  We had a power outage the day before, but it seems like a surprising corruption.  json_pp seems to like my .credentials.gmailieer.json file.  If it were a token expiration then I would think I would get a different error.

```
$ (cd ~/Maildir/account.gmail && gmi sync)
Failed to decode config file `/home/markgalassi/Maildir/account.gmail/.gmailieer.json`.
Traceback (most recent call last):
  File "/usr/local/bin/gmi", line 4, in <module>
    __import__('pkg_resources').run_script('lieer==1.2', 'gmi')
  File "/home/markgalassi/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/markgalassi/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/lieer-1.2-py3.8.egg/EGG-INFO/scripts/gmi", line 24, in <module>
  File "/usr/local/lib/python3.8/dist-packages/lieer-1.2-py3.8.egg/lieer/gmailieer.py", line 206, in main
  File "/usr/local/lib/python3.8/dist-packages/lieer-1.2-py3.8.egg/lieer/gmailieer.py", line 276, in sync
  File "/usr/local/lib/python3.8/dist-packages/lieer-1.2-py3.8.egg/lieer/gmailieer.py", line 272, in setup
  File "/usr/local/lib/python3.8/dist-packages/lieer-1.2-py3.8.egg/lieer/local.py", line 272, in load_repository
  File "/usr/local/lib/python3.8/dist-packages/lieer-1.2-py3.8.egg/lieer/local.py", line 90, in __init__
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by markgalassi** [comment]
Actually I think I can solve this one myself: turns out that there was a .gmaileer.json.bak file, which when I restored it to .gmaileer.json everything got fixed.

So my only remaining problem is with the obscure error message.  Sorry for the trouble.

**Comment by gauteh** [comment]
Nice, so it seems that .gmailieer.json got corrupted. Maybe in the power outage. In the error message this is the file that is mentioned, since you had the backup I think this ended surprisingly well :D
