### ISSUE TITLE
Allow mail not to be inside the notmuch db directory

### ISSUE THREAD

**Issue by kirelagin** [gauteh/lieer#214]
My mail directory is completely separate from the notmuch database:

```ini
[database]
path=/home/kirelagin/.local/share/notmuch
mail_root=/mnt/data/mail/kirelagin@gmail.com
```

I cd to `/mnt/data/mail/kirelagin@gmail.com` and run `gmi init kirelagin@gmail.com`, here is what I get:

```text
initializing repository in: /mnt/data/mail/kirelagin@gmail.com..
Traceback (most recent call last):
  File "/nix/store/pnxb89imalqlqxn0w5hjf27lznsh5sii-lieer-1.3/lib/python3.9/site-packages/lieer/local.py", line 280, in load_repository
    self.nm_dir  = db.get_directory (os.path.abspath(self.md))
  File "/nix/store/9cjbr05qa37ik9h0mk374smyks94v2zh-python3.9-notmuch-0.34.1/lib/python3.9/site-packages/notmuch/database.py", line 390, in get_directory
    raise FileError('Database().get_directory() called '
notmuch.errors.FileError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/pnxb89imalqlqxn0w5hjf27lznsh5sii-lieer-1.3/bin/.gmi-wrapped", line 25, in <module>
    g.main ()
  File "/nix/store/pnxb89imalqlqxn0w5hjf27lznsh5sii-lieer-1.3/lib/python3.9/site-packages/lieer/gmailieer.py", line 212, in main
    args.func (args)
  File "/nix/store/pnxb89imalqlqxn0w5hjf27lznsh5sii-lieer-1.3/lib/python3.9/site-packages/lieer/gmailieer.py", line 219, in initialize
    self.local.load_repository ()
  File "/nix/store/pnxb89imalqlqxn0w5hjf27lznsh5sii-lieer-1.3/lib/python3.9/site-packages/lieer/local.py", line 290, in load_repository
    raise Local.RepositoryException ("local mail repository not in notmuch db")
lieer.local.RepositoryException: local mail repository not in notmuch db
```

I don’t really understand why [this code](https://github.com/gauteh/lieer/blob/87e85ef546223d6a745e3fe95972fd1025c4c009/lieer/local.py#L328-L341) is doing this, but this doesn’t seem right?

**Comment by gauteh** [comment]
Yeah, I think that should be possible. What path: search matches the directory? And how do we verify that it is a valid notmuch directory?
