### ISSUE TITLE
gmi send error on dry-run

### ISSUE THREAD

**Issue by mechanicalamit** [gauteh/lieer#259]
Using Release v1.5 (commit 85f515125)

```python
path: /home/user/notmuch/
dry-run:  True
sending message, from: Amit Dhingra <fakemail@gmail.com>..
Traceback (most recent call last):
  File "/home/user/build/lieer/./gmi", line 24, in <module>
    g.main ()
  File "/home/user/build/lieer/lieer/gmailieer.py", line 418, in main
    args.func(args)
  File "/home/user/build/lieer/lieer/gmailieer.py", line 1099, in send
    self.vprint("message sent successfully: %s" % msg["id"])
                                                  ~~~^^^^^^
TypeError: byte indices must be integers or slices, not str
``` 

I think msg is assigned (again) in [line 1093](https://github.com/gauteh/lieer/blob/85f5151251edfbcb0c05e941296f81775b2e4d73/lieer/gmailieer.py#L1093) which is `not dry_run`, so does not get assigned during the dry-run.

The print line 1097 is outside and errors since msg has stale data from stdin.read() on line 1021

**Comment by gauteh** [comment]
Fixed in #260.
