### ISSUE TITLE
module 'notmuch2' has no attribute 'Database'

### ISSUE THREAD

**Issue by RobinBeekhof** [gauteh/lieer#262]
When I run `gmi sync` I get the following error. This used to work fine before.

`gmi sync
Traceback (most recent call last):
  File "/opt/homebrew/bin/gmi", line 24, in <module>
    g.main ()
  File "/opt/homebrew/lib/python3.11/site-packages/lieer/gmailieer.py", line 234, in main
    args.func (args)
  File "/opt/homebrew/lib/python3.11/site-packages/lieer/gmailieer.py", line 305, in sync
    self.setup (args, args.dry_run, True)
  File "/opt/homebrew/lib/python3.11/site-packages/lieer/gmailieer.py", line 301, in setup
    self.local.load_repository (block)
  File "/opt/homebrew/lib/python3.11/site-packages/lieer/local.py", line 330, in load_repository
    with notmuch2.Database () as db:
         ^^^^^^^^^^^^^^^^^
AttributeError: module 'notmuch2' has no attribute 'Database'`

notmuch itself works fine, do you have any idea what could cause this error?

**Comment by gauteh** [comment]
Think this is a notmuch -> notmuch2 issue.
